/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AllAuthorApiInfoArtistsInnerLifeSpan } from './allAuthorApiInfoArtistsInnerLifeSpan';


export interface AllAuthorApiInfoArtistsInner { 
    id?: string;
    type?: string;
    name?: string;
    'sort-name'?: string;
    'life-span'?: AllAuthorApiInfoArtistsInnerLifeSpan;
}

