/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AllWorksApiInfoWorksInnerRelationsInner } from './allWorksApiInfoWorksInnerRelationsInner';


export interface AllWorksApiInfoWorksInner { 
    id?: string;
    title?: string;
    relations?: Array<AllWorksApiInfoWorksInnerRelationsInner>;
}

