/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AllWorksApiInfoWorksInnerRelationsInnerArtist { 
    id?: string;
    name?: string;
    'sort-name'?: string;
    disambiguation?: string;
}

