/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthorApiInfo } from './authorApiInfo';


export interface AuthorWithScoreCount { 
    author: AuthorApiInfo;
    /**
     * Number of scores by this author
     */
    count: number;
    /**
     * Last update time for this author\'s score count
     */
    updatedAt?: string;
}

