/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorApiInfo { 
    id: string;
    name: string;
    birth?: string;
    bio: string;
    image?: string;
    link?: string;
}

