/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorApiInfo { 
    id?: string;
    mbid?: string;
    name?: string;
    disambiguation?: string;
    country?: string;
    type?: string;
    gender?: string;
    lifeSpanBegin?: string;
    lifeSpanEnd?: string;
    lifeSpanEnded?: boolean;
    /**
     * URL-friendly slug for the author
     */
    slug?: string;
    sortName?: string;
}

