/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreApiInfo { 
    id?: string;
    mbid?: string;
    name?: string;
    /**
     * Number of scores linked to this genre (non-deleted)
     */
    scoreCount?: number;
    /**
     * URL-friendly slug for the genre
     */
    slug?: string;
}

