/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenreTreeNode { 
    /**
     * MusicBrainz ID (MBID) of the genre (stored in genre_tree.genre_id)
     */
    mbid: string;
    name?: string;
    parent_id?: string | null;
    children?: Array<GenreTreeNode>;
}

