/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HarmonyEntry { 
    /**
     * Measure number (1-based)
     */
    measure: number;
    /**
     * Root note of the chord (e.g., C, D, F#)
     */
    root: string;
    /**
     * Chord type (e.g., major, minor-seventh, dominant-seventh, diminished)
     */
    kind: string;
    /**
     * Beat position within the measure (1-based)
     */
    beat: number;
    /**
     * Optional bass note for slash chords (e.g., Bb)
     */
    bass?: string | null;
}

