/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MusicBrainzServiceLifeSpan } from './musicBrainzServiceLifeSpan';


export interface MbAuthorApiInfo { 
    id?: string;
    type?: string;
    name?: string;
    'sort-name'?: string;
    disambiguation?: string;
    gender?: string;
    country?: string;
    'life-span'?: MusicBrainzServiceLifeSpan;
}

