/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScoreApiInfo { 
    id?: string;
    mbid?: string;
    title?: string;
    author?: string;
    author_id?: string;
    sortName?: string;
    version?: number;
    tracks_count?: number;
    hand_separated?: boolean;
    has_lyrics?: boolean;
    measures?: number;
    duration?: number;
    genre?: string;
    genre_id?: string;
    grade?: number;
    uploaded_at?: string;
    owner_id?: string;
    owner?: string;
    updated_at?: string;
    has_files?: boolean;
    image?: string;
    study_tracks?: Array<number>;
    mutableSlug?: string;
    immutableSlug?: string;
    tempo?: number;
    publicDomain?: boolean;
    exercise?: boolean;
    playCount?: number;
}

