/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenreApiInfo } from './genreApiInfo';


export interface ScoreGenreBrowseGet200ResponseInner { 
    genre: GenreApiInfo;
    count: number;
    updatedAt: string;
}

