/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScorePlayStatsPostRequestAssessment } from './scorePlayStatsPostRequestAssessment';


export interface ScorePlayStatsPostRequest { 
    id: string;
    title?: string;
    author?: string;
    played_at?: string;
    tonic?: string;
    mode?: string;
    genre?: string;
    genre_id?: string;
    assessment?: ScorePlayStatsPostRequestAssessment;
}

