/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScoreStatsGet200Response { 
    /**
     * Number of public domain scores
     */
    'public-domain': number;
    /**
     * Number of copyrighted scores
     */
    copyrighted: number;
}

