/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScorePlayStatsPostRequestAssessment { 
    accuracy?: number;
    bad?: number;
    late?: number;
    start?: number;
    end?: number;
    total?: number;
}

