/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HarmonyEntry } from './harmonyEntry';
import { YoutubeLink } from './youtubeLink';


export interface ScoreApiInfo { 
    id?: string;
    mbid?: string;
    title?: string;
    author?: string;
    author_id?: string;
    author_mbid?: string;
    author_slug?: string;
    sortName?: string;
    version?: number;
    tracks_count?: number;
    hand_separated?: boolean;
    has_lyrics?: boolean;
    measures?: number;
    duration?: number;
    genre?: string;
    genre_id?: string;
    genre_slug?: string;
    grade?: number;
    uploaded_at?: string;
    owner_id?: string;
    owner?: string;
    updated_at?: string;
    has_files?: boolean;
    image?: string;
    study_tracks?: Array<number>;
    mutableSlug?: string;
    immutableSlug?: string;
    tempo?: number;
    publicDomain?: boolean;
    exercise?: boolean;
    playCount?: number;
    /**
     * The tonic note of the piece (e.g., C, D, E)
     */
    tonic?: string;
    /**
     * The mode of the piece (e.g., major, minor)
     */
    mode?: string;
    /**
     * The full key signature (e.g., C major, D minor)
     */
    fullKey?: string;
    /**
     * List of chord changes per measure and beat
     */
    harmony?: Array<HarmonyEntry> | null;
    /**
     * Description textuelle de la partition
     */
    description?: string;
    /**
     * List of YouTube links associated with the score
     */
    youtubeLinks?: Array<YoutubeLink> | null;
}

