/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScoreApiInfo { 
    id?: string;
    title: string;
    author: string;
    author_id?: string;
    version?: number;
    year: number;
    tracks_count?: number;
    hand_separated?: boolean;
    has_lyrics?: boolean;
    measures?: number;
    duration?: number;
    genre?: string;
    genre_id?: string;
    grade?: number;
    uploaded_at?: string;
    uploaded_by_id?: string;
    uploaded_by_name?: string;
    updated_at?: string;
    has_mxml?: boolean;
    has_pdf?: boolean;
    image?: string;
}

