/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WorkloadApiInfo { 
    id?: number;
    kind?: string;
    createdAt?: string;
    scoreId?: string;
    status?: WorkloadApiInfo.StatusEnum;
    errorMessage?: string;
    /**
     * Duration in milliseconds
     */
    duration?: number;
    workloadSize?: number;
}
export namespace WorkloadApiInfo {
    export const StatusEnum = {
        Pending: 'PENDING',
        Running: 'RUNNING',
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


