/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface YoutubeVideoApiInfo { 
    /**
     * YouTube video ID
     */
    videoId?: string;
    /**
     * Video title
     */
    title?: string;
    /**
     * Video description snippet
     */
    description?: string;
    /**
     * URL of the video thumbnail
     */
    thumbnailUrl?: string;
    /**
     * Name of the YouTube channel
     */
    channelTitle?: string;
    /**
     * Publication date of the video
     */
    publishedAt?: string;
}

