/**
 * PianoML API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface YoutubeLink { 
    /**
     * YouTube URL
     */
    url: string;
    /**
     * Ranking or priority for the link (lower is better)
     */
    rank?: number;
}

