
spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.url=jdbc:postgresql://localhost:5432/pianoml
spring.datasource.username=web
spring.datasource.password=web

spring.cloud.gcp.sql.enabled=false


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.default-schema=pianoml

jwt.secret=your-super-secret-key-that-is-long-enough
jwt.expiration-ms=3600000

# AWS S3 Configuration
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=efa4c55267d6f582616c2c2fe1fced3c
spring.cloud.aws.credentials.secret-key=f41887e7ec16826a78c1702b1a94a239707ad485d4895dc26d24a46fc163baaa
aws.s3.bucket-name=pianoml-media
spring.cloud.aws.endpoint=https://a875d3bbcfc175fef5a7d5506780ff7f.r2.cloudflarestorage.com
