
spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/pianoml
spring.cloud.gcp.sql.enabled=false

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.default-schema=pianoml

jwt.secret=your-super-secret-key-that-is-long-enough
jwt.expiration-ms=3600000

# AWS S3 Configuration
spring.cloud.aws.region.static=us-east-1
#spring.cloud.aws.credentials.access-key=access-key-id
#spring.cloud.aws.credentials.secret-key=secret-access-key
aws.s3.bucket-name=pianoml-media
spring.cloud.aws.endpoint=https://a875d3bbcfc175fef5a7d5506780ff7f.r2.cloudflarestorage.com
