
name: Build and Push to Artifact Registry

on:
  push:
    branches: ["deploy"]
  pull_request:
    branches: ["deploy"]

env:
  PROJECT_ID: sectrack
  REGION: northamerica-northeast1
  GAR_LOCATION: northamerica-northeast1-docker.pkg.dev/sectrack/repo/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: compile
        working-directory: ./backend
        run: mvn --batch-mode --update-snapshots install

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCR_PUSH_SECRET }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build -t northamerica-northeast1-docker.pkg.dev/sectrack/pianoml:latest -f backend/Dockerfile ./backend
#
        working-directory: ./backend

      - name: Push image
        run: docker push northamerica-northeast1-docker.pkg.dev/sectrack/pianoml:latest 

# name: Build and Push Docker image to GCR

# on:
#   push:
#     branches:
#       - main
#       - deploy

# jobs:
#   build-and-push:
#     #if: ${{ github.event.workflow_run.conclusion == 'success' }}
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 17
#         uses: actions/setup-java@v4
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#           cache: maven
#       - name: compile
#         working-directory: ./backend
#         run: mvn --batch-mode --update-snapshots install

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       - name: Authenticate to Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           credentials_json: ${{ secrets.GCR_PUSH_SECRET }}
#       - name: 'Set up Cloud SDK'
#         uses: 'google-github-actions/setup-gcloud@v2'
#       - name: Build Docker image
#         run: |
#           docker build -t northamerica-northeast1-docker.pkg.dev/sectrack/pianoml:latest -f backend/Dockerfile ./backend
#       - name: GitHub Container Registry login
#         uses: docker/login-action@v3
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.CR_PAT_SECRET }}
#       - name: Push Docker image to GitHub Container Registry
#         run: |
#           docker tag northamerica-northeast1-docker.pkg.dev/sectrack/pianoml:latest ghcr.io/${{ github.repository_owner }}/pianoml:latest
#           docker push northamerica-northeast1-docker.pkg.dev/sectrack/pianoml:latest
